import {
  IFilamentItem,
  IAccessoryItem,
  IPrintingServicePackage,
  IPrintProfileItem,
  IShopModelItem,
} from '@/backend/domain/shop';

export const SHOP_FILAMENTS: IFilamentItem[] = [
  {
    id: 'fil-bambu-pla-basic-white',
    type: 'filament',
    name: 'Bambu Lab PLA Basic 1.75mm (Kèm Lõi Spool RFID)',
    brand: 'Bambu Lab',
    material: 'PLA',
    colorName: 'Jade White (Trắng Ngọc)',
    colorHex: '#f8fafc',
    weightKg: 1.0,
    diameterMm: 1.75,
    priceVnd: 420000,
    originalPriceVnd: 470000,
    inStock: true,
    stockCount: 38,
    rating: 4.9,
    reviewsCount: 142,
    nozzleTempRange: '190°C - 230°C',
    bedTempRange: '35°C - 55°C',
    printSpeedRange: 'Lên tới 300 mm/s',
    description: 'Cuộn nhựa chính hãng Bambu Lab tích hợp chip RFID tự động nhận diện thông số trên dòng máy X1, P1, A1. Bề mặt láng mịn, ít văng sợi.',
    highlights: ['Tích hợp chip RFID tự nhận diện', 'In tốc độ cao không nghẹt đầu', 'Độ bám dính bàn in xuất sắc'],
    thumbnailUrl: '/thumbnails/spool-pla.svg',
    badge: 'Bán chạy',
  },
  {
    id: 'fil-bambu-petg-cf-black',
    type: 'filament',
    name: 'Bambu Lab PETG-CF Sợi Carbon Chịu Lực Cao',
    brand: 'Bambu Lab',
    material: 'PETG-CF',
    colorName: 'Charcoal Black (Đen Than)',
    colorHex: '#1e293b',
    weightKg: 1.0,
    diameterMm: 1.75,
    priceVnd: 680000,
    originalPriceVnd: 750000,
    inStock: true,
    stockCount: 19,
    rating: 4.9,
    reviewsCount: 88,
    nozzleTempRange: '230°C - 260°C',
    bedTempRange: '65°C - 75°C',
    printSpeedRange: '50 - 200 mm/s',
    description: 'Pha trộn sợi carbon micro gia cường giúp tăng 50% độ cứng uốn so với PETG thường. Bề mặt hoàn thiện nhám mờ sang trọng, che hoàn toàn đường vân lớp in.',
    highlights: ['Gia cường sợi Carbon chịu lực', 'Bề mặt mờ che đường layer', 'Chống biến dạng nhiệt 75°C'],
    thumbnailUrl: '/thumbnails/spool-cf.svg',
    badge: 'Khuyên dùng',
  },
  {
    id: 'fil-esun-pla-plus-grey',
    type: 'filament',
    name: 'eSUN PLA+ (PLA Pro) Độ Dẻo Dai Cao Kháng Va Đập',
    brand: 'eSUN',
    material: 'PLA',
    colorName: 'Silver Grey (Xám Bạc)',
    colorHex: '#94a3b8',
    weightKg: 1.0,
    diameterMm: 1.75,
    priceVnd: 320000,
    originalPriceVnd: 350000,
    inStock: true,
    stockCount: 52,
    rating: 4.8,
    reviewsCount: 310,
    nozzleTempRange: '205°C - 225°C',
    bedTempRange: '50°C - 60°C',
    printSpeedRange: '60 - 250 mm/s',
    description: 'Dòng nhựa PLA+ huyền thoại của eSUN, dai gấp 5 lần PLA thông thường, khó gãy giòn, tương thích tốt với mọi máy in FDM thị trường.',
    highlights: ['Kháng nứt gãy va đập vượt trội', 'Màu sắc đồng đều, ổn định', 'Tương thích 99% máy in FDM'],
    thumbnailUrl: '/thumbnails/spool-pla-plus.svg',
    badge: 'Bán chạy',
  },
  {
    id: 'fil-sunlu-tpu-95a-black',
    type: 'filament',
    name: 'Sunlu TPU 95A Nhựa Dẻo Co Giãn Đàn Hồi',
    brand: 'Sunlu',
    material: 'TPU',
    colorName: 'Pure Black (Đen Tuyền)',
    colorHex: '#0f172a',
    weightKg: 1.0,
    diameterMm: 1.75,
    priceVnd: 450000,
    originalPriceVnd: 490000,
    inStock: true,
    stockCount: 15,
    rating: 4.7,
    reviewsCount: 65,
    nozzleTempRange: '200°C - 220°C',
    bedTempRange: '30°C - 50°C',
    printSpeedRange: '30 - 80 mm/s',
    description: 'Nhựa nhiệt dẻo polyurethane đàn hồi cao, chống dầu mỡ và mài mòn, lý tưởng để in ốp lưng điện thoại, bánh xe robot, đệm cao su giảm chấn.',
    highlights: ['Độ đàn hồi Shore 95A', 'Kháng dầu và hóa chất', 'Bền bỉ uốn cong không gãy'],
    thumbnailUrl: '/thumbnails/spool-tpu.svg',
  },
  {
    id: 'fil-polymaker-asa-white',
    type: 'filament',
    name: 'Polymaker PolyLite ASA Chống UV & Chịu Thời Tiết Ngoài Trời',
    brand: 'Polymaker',
    material: 'ASA',
    colorName: 'Pure White (Trắng Tinh)',
    colorHex: '#ffffff',
    weightKg: 1.0,
    diameterMm: 1.75,
    priceVnd: 590000,
    originalPriceVnd: 650000,
    inStock: true,
    stockCount: 12,
    rating: 4.8,
    reviewsCount: 43,
    nozzleTempRange: '240°C - 260°C',
    bedTempRange: '80°C - 100°C',
    printSpeedRange: '40 - 100 mm/s',
    description: 'Vật liệu thay thế hoàn hảo cho ABS. Kháng tia cực tím UV và mưa nắng ngoài trời, không ố vàng, chịu nhiệt lên đến 95°C.',
    highlights: ['Chống tia UV ngoài trời không ố vàng', 'Chịu nhiệt tới 95°C', 'Độ bền cơ tính công nghiệp'],
    thumbnailUrl: '/thumbnails/spool-asa.svg',
    badge: 'Khuyên dùng',
  },
  {
    id: 'fil-elegoo-resin-8k-grey',
    type: 'filament',
    name: 'Elegoo 8K Standard Photopolymer Resin In SLA Siêu Mịn 1000g',
    brand: 'Elegoo',
    material: 'Resin',
    colorName: 'Space Grey (Xám Không Gian)',
    colorHex: '#64748b',
    weightKg: 1.0,
    diameterMm: 0,
    priceVnd: 520000,
    originalPriceVnd: 580000,
    inStock: true,
    stockCount: 24,
    rating: 4.9,
    reviewsCount: 118,
    nozzleTempRange: 'N/A (SLA)',
    bedTempRange: '25°C - 30°C',
    printSpeedRange: '1.5 - 2.5s / layer',
    description: 'Resin chất lượng cao chuyên dụng cho màn hình LCD 8K và 12K. Độ co ngót thấp, hiển thị siêu sắc nét các nếp gấp mô hình anime và tượng mini.',
    highlights: ['Tối ưu cho màn hình 8K/12K', 'Độ co ngót cực thấp dưới 1%', 'Chi tiết siêu mịn 0.02mm'],
    thumbnailUrl: '/thumbnails/bottle-resin.svg',
    badge: 'Mới ra mắt',
  },
];

export const SHOP_ACCESSORIES: IAccessoryItem[] = [
  {
    id: 'acc-bambu-hotend-hardened-04',
    type: 'accessory',
    name: 'Cụm Hotend Thép Tôi Cứng Complete Hardened Steel 0.4mm (Bambu X1/P1)',
    brand: 'Bambu Lab',
    subCategory: 'hotend',
    compatibility: ['Bambu Lab X1-Carbon', 'Bambu Lab P1S', 'Bambu Lab P1P'],
    priceVnd: 550000,
    originalPriceVnd: 620000,
    inStock: true,
    stockCount: 22,
    rating: 4.9,
    reviewsCount: 94,
    description: 'Bộ Hotend tích hợp đầy đủ đầu phun thép tôi 55 HRC, quạt tản nhiệt, thanh nhiệt gốm và cảm biến nhiệt. Chuyên dụng in sợi Carbon CF/GF không lo mòn nozzle.',
    specs: {
      'Vật liệu đầu phun': 'Thép tôi cứng Hardened Steel 55 HRC',
      'Đường kính lỗ': '0.4 mm',
      'Nhiệt độ tối đa': '300°C',
      'Loại sợi phù hợp': 'PLA, PETG, ABS, PA-CF, PETG-CF, Glow in dark',
    },
    thumbnailUrl: '/thumbnails/voron-toolhead.svg',
    badge: 'Chính hãng',
  },
  {
    id: 'acc-bambu-pei-sheet-textured',
    type: 'accessory',
    name: 'Bàn In Từ Tính PEI Nhám Hai Mặt Textured PEI Plate 256x256mm',
    brand: 'Bambu Lab',
    subCategory: 'build_plate',
    compatibility: ['Bambu Lab X1-Carbon', 'Bambu Lab P1S', 'Bambu Lab P1P', 'Bambu Lab A1'],
    priceVnd: 680000,
    originalPriceVnd: 750000,
    inStock: true,
    stockCount: 31,
    rating: 5.0,
    reviewsCount: 167,
    description: 'Mặt bàn in phủ PEI nhám bột tĩnh điện chống trầy. Bám dính cực tốt khi bàn nóng, tự động tách mô hình khi bàn nguội mà không cần cạy.',
    specs: {
      'Kích thước': '256 x 256 mm',
      'Bề mặt': 'Textured PEI nhám hạt mờ 2 mặt',
      'Độ dày lá thép': '0.5 mm lò xo bimetal dẻo',
      'Chịu nhiệt': 'Lên tới 120°C',
    },
    thumbnailUrl: '/thumbnails/bambu-acc.svg',
    badge: 'Được mua nhiều',
  },
  {
    id: 'acc-sunlu-dryer-s2',
    type: 'accessory',
    name: 'Máy Sấy Cuộn Nhựa Chuyên Dụng Sunlu Filadryer S2 Có Màn Hình Cảm Ứng',
    brand: 'Sunlu',
    subCategory: 'dryer',
    compatibility: ['Cuộn nhựa 1kg', 'Cuộn nhựa 0.5kg', 'Đường kính cuộn ≤210mm'],
    priceVnd: 1150000,
    originalPriceVnd: 1350000,
    inStock: true,
    stockCount: 9,
    rating: 4.8,
    reviewsCount: 73,
    description: 'Hệ thống sấy nhiệt 360 độ tuần hoàn khép kín, triệt tiêu ẩm mốc cho nhựa PETG, TPU, Nylon, PLA. Cho phép vừa sấy vừa luồn sợi in trực tiếp.',
    specs: {
      'Nhiệt độ sấy': '35°C - 70°C',
      'Màn hình': 'Cảm ứng LED 2.8 inch',
      'Hẹn giờ': '1 - 99 giờ',
      'Cảm biến ẩm': 'Hiển thị % RH theo thời gian thực',
    },
    thumbnailUrl: '/thumbnails/rugged-box.svg',
    badge: 'Độ bền cao',
  },
  {
    id: 'acc-cht-nozzle-bimetal-04',
    type: 'accessory',
    name: 'Đầu Phun Tốc Độ Cao CHT Bimetal High-Flow M6 0.4mm',
    brand: 'Phaetus',
    subCategory: 'nozzle',
    compatibility: ['Ender 3 V3 / SE', 'Creality K1 / K1 Max', 'Voron StealthBurner', 'Anycubic Kobra'],
    priceVnd: 280000,
    originalPriceVnd: 320000,
    inStock: true,
    stockCount: 45,
    rating: 4.8,
    reviewsCount: 52,
    description: 'Thiết kế 3 rãnh dẫn nhiệt lõi đồng chia nhỏ dòng nhựa tan chảy nhanh gấp đôi, nâng lưu lượng đùn (flow rate) từ 15mm³/s lên tới 35mm³/s.',
    specs: {
      'Chuẩn ren': 'M6',
      'Đường kính': '0.4 mm',
      'Vật liệu': 'Lõi đồng dẫn nhiệt + Đầu thép cứng',
      'Lưu lượng tối đa': '35 mm³/s',
    },
    thumbnailUrl: '/thumbnails/gear.svg',
  },
  {
    id: 'acc-tools-plato-kit',
    type: 'accessory',
    name: 'Bộ Combo Kìm Cắt Mô Hình Plato 170 + Dao Cạo Bàn In + Kim Thông Nozzle',
    brand: 'Plato & MakerHub',
    subCategory: 'tools',
    compatibility: ['Phổ thông mọi dòng máy in 3D'],
    priceVnd: 145000,
    originalPriceVnd: 180000,
    inStock: true,
    stockCount: 80,
    rating: 4.9,
    reviewsCount: 220,
    description: 'Bộ dụng cụ cơ bản không thể thiếu: Kìm cắt chân support siêu sát, dao cạo inox vát cạnh bóc mẫu không xước PEI, 5 kim thông nghẹt đầu phun 0.4mm.',
    specs: {
      'Bao gồm': '1 Kìm Plato 170, 1 Dao cạo vát góc, 5 Kim thông 0.4mm',
      'Chất liệu kìm': 'Thép cacbon cao cấp tôi dầu',
    },
    thumbnailUrl: '/thumbnails/drill-guide.svg',
    badge: 'Được mua nhiều',
  },
];

export const SHOP_PRINTING_SERVICES: IPrintingServicePackage[] = [
  {
    id: 'srv-fdm-fast',
    type: 'service',
    name: 'In 3D FDM Tốc Độ Cao (Bambu Lab X1C / P1S)',
    technology: 'FDM High-Speed',
    pricePerGramVnd: 600,
    minOrderVnd: 50000,
    turnaroundTime: '12h - 24h siêu tốc',
    precision: '±0.1 mm',
    maxVolumeMm: { x: 256, y: 256, z: 256 },
    suitableFor: ['Vỏ hộp linh kiện điện tử', 'Chi tiết cơ khí test mẫu', 'Mô hình kiến trúc', 'Dụng cụ sinh hoạt'],
    materialsAvailable: ['PLA Basic', 'PLA Tough', 'PETG Chịu nhiệt', 'ABS Kháng lực'],
    description: 'Dàn máy Bambu Lab thế hệ mới in với tốc độ 300mm/s, hoàn thiện nhanh chóng đơn hàng trong ngày với độ chính xác cao và giá thành kinh tế nhất.',
    thumbnailUrl: '/thumbnails/benchy.svg',
    badge: 'Siêu Tốc 24h',
  },
  {
    id: 'srv-sla-resin-8k',
    type: 'service',
    name: 'In 3D SLA Resin Siêu Mịn 8K (Elegoo Saturn 4 Ultra)',
    technology: 'SLA Resin 8K',
    pricePerGramVnd: 1800,
    minOrderVnd: 80000,
    turnaroundTime: '24h - 48h',
    precision: '±0.02 mm (Cực mịn không thấy vân)',
    maxVolumeMm: { x: 218, y: 122, z: 220 },
    suitableFor: ['Figure Anime / Game chi tiết cao', 'Mặt nhẫn & Khuôn đúc trang sức', 'Răng hàm nha khoa', 'Mô hình điêu khắc phức tạp'],
    materialsAvailable: ['Resin 8K Tiêu chuẩn Xám', 'Resin ABS-Like Dẻo Dai', 'Resin Castable Đúc Kim Loại'],
    description: 'Công nghệ quang trùng hợp màn hình đơn sắc Mono LCD 8K với kích thước điểm ảnh chỉ 19x24 micromet. Bề mặt nhẵn bóng như đúc khuôn nhựa công nghiệp.',
    thumbnailUrl: '/thumbnails/oni-mask.svg',
    badge: 'Độ Mịn 8K',
  },
  {
    id: 'srv-ams-multicolor',
    type: 'service',
    name: 'In 3D Đa Màu Tự Động AMS (Lên Tới 8 Màu Đồng Thời)',
    technology: 'AMS Multi-Color',
    pricePerGramVnd: 950,
    minOrderVnd: 70000,
    turnaroundTime: '24h - 48h',
    precision: '±0.1 mm',
    maxVolumeMm: { x: 256, y: 256, z: 256 },
    suitableFor: ['Logo công ty & Biển hiệu', 'Quà tặng lưu niệm màu sắc', 'Mô hình đồ chơi trẻ em', 'Trang trí nội thất'],
    materialsAvailable: ['PLA Đa sắc màu', 'PETG Phối màu', 'PLA Glow phát quang'],
    description: 'Hệ thống nạp vật liệu tự động chuyển màu liên tục trong quá trình in, không cần dán đề can hay sơn xịt thủ công. Màu sắc sắc nét bền vững theo thời gian.',
    thumbnailUrl: '/thumbnails/hueforge.svg',
    badge: 'Đa Màu AMS',
  },
  {
    id: 'srv-engineering-cf',
    type: 'service',
    name: 'In Nhựa Kỹ Thuật Carbon Fiber PA-CF / PETG-CF Chịu Lực',
    technology: 'Engineering PA-CF',
    pricePerGramVnd: 1500,
    minOrderVnd: 100000,
    turnaroundTime: '24h - 48h',
    precision: '±0.08 mm',
    maxVolumeMm: { x: 256, y: 256, z: 256 },
    suitableFor: ['Bánh răng & Chi tiết chịu ma sát', 'Ngàm gắn máy ảnh / flycam', 'Phụ tùng ô tô xe máy', 'Đồ gá Jigs công nghiệp'],
    materialsAvailable: ['Nylon PA12-CF', 'PETG-CF', 'Polycarbonate PC', 'ASA'],
    description: 'In trên máy buồng sấy nhiệt độ cao với đầu phun thép tôi cứng. Tạo ra các chi tiết cơ khí có độ cứng uốn, chống va đập và chịu nhiệt tới 150°C.',
    thumbnailUrl: '/thumbnails/voron-toolhead.svg',
    badge: 'Chịu Lực Cao',
  },
];

export const SHOP_PRINT_PROFILES: IPrintProfileItem[] = [
  {
    id: 'prof-bambu-x1c-speed-016',
    type: 'profile',
    title: 'Bambu Lab X1C / P1S – Tối Ưu Tốc Độ Cao 0.16mm (Scarf Joint Seam)',
    printerModel: 'Bambu Lab X1-Carbon / P1S / A1',
    slicer: 'OrcaSlicer',
    filamentType: 'PLA / PLA+',
    layerHeightMm: '0.16 mm',
    nozzleSizeMm: '0.4 mm',
    estimatedSpeedMmS: 320,
    priceVnd: 0,
    downloads: 1450,
    rating: 4.9,
    description: 'Profile chuẩn thi đấu in tốc độ cao: Ẩn đường nối giáp mối (Scarf Joint Seam) 90%, góc cua mượt không rung lắc nhờ tối ưu hoá gia tốc và Flow Rate.',
    highlights: ['Bật tính năng giấu mối in Scarf Joint', 'Tốc độ thành ngoài 150mm/s sắc nét', 'Thời gian in giảm 25%'],
    fileName: 'Bambu_X1C_SpeedMaster_016.orca_printer',
    isVerified: true,
    badge: 'Đã kiểm chứng',
  },
  {
    id: 'prof-k1-input-shaping',
    type: 'profile',
    title: 'Creality K1 / K1C Max – Input Shaping & Fast Draft 0.20mm',
    printerModel: 'Creality K1 / K1 Max / K1C',
    slicer: 'Creality Print',
    filamentType: 'Hyper PLA / PETG',
    layerHeightMm: '0.20 mm',
    nozzleSizeMm: '0.4 mm',
    estimatedSpeedMmS: 400,
    priceVnd: 0,
    downloads: 890,
    rating: 4.8,
    description: 'Cấu hình tối ưu rung lắc buồng kín cho dòng máy CoreXY Creality K1 series, giảm thiểu hiện tượng bóng mờ (ghosting) ở tốc độ cao.',
    highlights: ['Triệt tiêu hiện tượng bóng mờ (Ringing)', 'In Benchy chỉ mất 16 phút', 'Cầu nối mượt không sệ'],
    fileName: 'Creality_K1_FastDraft_020.cp_profile',
    isVerified: true,
    badge: 'Tối ưu tốc độ',
  },
  {
    id: 'prof-voron-orca-pip',
    type: 'profile',
    title: 'Voron 2.4 StealthBurner – Cấu Hình Khớp In Liền (Print-in-Place Clearance 0.15mm)',
    printerModel: 'Voron 2.4 / Trident R2',
    slicer: 'OrcaSlicer',
    filamentType: 'ABS / ASA / PETG',
    layerHeightMm: '0.16 mm',
    nozzleSizeMm: '0.4 mm',
    estimatedSpeedMmS: 250,
    priceVnd: 25000,
    downloads: 410,
    rating: 5.0,
    description: 'Hiệu chỉnh dung sai cơ khí khắt khe (xy hole/contour compensation) để in các mô hình rồng uốn lượn, xích chuyền hay vòng bi quay ngay lập tức sau khi gỡ khỏi bàn in.',
    highlights: ['Dung sai khe hở 0.15mm chuẩn xác', 'Không bị dính chết khớp chuyển động', 'Tương thích máy Voron & Bambu'],
    fileName: 'Voron_Orca_PrintInPlace_Pro.3mf',
    isVerified: true,
    badge: 'Cơ khớp mượt',
  },
  {
    id: 'prof-sla-miniature-detail',
    type: 'profile',
    title: 'Elegoo Saturn 4 & Mars 4 – Anti-Aliasing 8x Figure Tượng Nét Từng Nanomet',
    printerModel: 'Elegoo Saturn 4 Ultra / Anycubic Photon Mono M5',
    slicer: 'PrusaSlicer',
    filamentType: 'Resin 8K / Tough Resin',
    layerHeightMm: '0.03 mm',
    nozzleSizeMm: 'N/A (SLA)',
    estimatedSpeedMmS: 0,
    priceVnd: 35000,
    downloads: 280,
    rating: 4.9,
    description: 'Thiết lập chống răng cưa Anti-aliasing mức 8 kèm khử bóng bề mặt và cấu hình chân chống Support siêu mảnh (Light Support đầu tiếp xúc 0.25mm dễ tách).',
    highlights: ['Khử hoàn toàn vết vân voxel', 'Đầu ghim support 0.25mm không rỗ mặt', 'Tỷ lệ in thành công 98%'],
    fileName: 'SLA_Figure_Saturn4_ProDetail.cfg',
    isVerified: true,
    badge: 'Đã kiểm chứng',
  },
];

export const SHOP_MODELS: IShopModelItem[] = [
  // --- MÔ HÌNH FREE ---
  {
    id: 'mod-benchy',
    type: 'model',
    title: '3D Benchy – Thuyền Kiểm Chuẩn Máy In 3D Toàn Cầu',
    author: 'CreativeTools',
    isFree: true,
    priceVnd: 0,
    category: 'tools',
    formats: ['.STL', '.3MF', '.STEP'],
    downloads: 45200,
    likes: 12400,
    rating: 5.0,
    reviewsCount: 890,
    difficulty: 'Dễ in',
    sampleModelId: 'benchy',
    printTimeEstimate: '38 phút',
    filamentWeightEstimate: '14g',
    description: 'Biểu tượng kiểm định khả năng in 3D FDM: kiểm tra độ võng (overhang), cầu nối (bridge), hình trụ tròn (ống khói) và độ bám dính đáy thuyền.',
    features: ['Không cần bật Support', 'Thời gian in nhanh', 'File .3MF đã cắt lớp sẵn'],
    thumbnailUrl: '/thumbnails/benchy.svg',
    badge: 'Miễn phí 100%',
  },
  {
    id: 'mod-dragon',
    type: 'model',
    title: 'Articulated Crystal Dragon V3 – Rồng Pha Lê Khớp Uốn Liền Khối',
    author: 'Cinderwing3D',
    isFree: true,
    priceVnd: 0,
    category: 'gadgets',
    formats: ['.STL', '.3MF'],
    downloads: 28900,
    likes: 9100,
    rating: 4.9,
    reviewsCount: 610,
    difficulty: 'Trung bình',
    sampleModelId: 'dragon',
    printTimeEstimate: '4h 15m',
    filamentWeightEstimate: '85g',
    description: 'Mô hình rồng khớp cầu in một lần duy nhất không cần lắp ráp (Print-In-Place). Toàn bộ thân uốn lượn mềm mại như thật, gai pha lê vát cạnh sắc nét.',
    features: ['Khớp in liền khối Print-In-Place', 'Hiệu ứng tuyệt đẹp với nhựa Silk', 'Thích hợp làm đồ chơi xả stress'],
    thumbnailUrl: '/thumbnails/dragon.svg',
    badge: 'Miễn phí 100%',
  },
  {
    id: 'mod-planetary-gear',
    type: 'model',
    title: 'Planetary Gear Bearing – Vòng Bi Bánh Răng Hành Tinh Cơ Khí',
    author: 'Emmett',
    isFree: true,
    priceVnd: 0,
    category: 'mechanical',
    formats: ['.STL', '.STEP'],
    downloads: 18400,
    likes: 5400,
    rating: 4.8,
    reviewsCount: 320,
    difficulty: 'Dễ in',
    sampleModelId: 'gear',
    printTimeEstimate: '1h 10m',
    filamentWeightEstimate: '32g',
    description: 'Cụm bánh răng hành tinh xoay trơn tru với 6 vệ tinh bánh răng liên hoàn. Không cần đai ốc hay bạc đạn phụ kiện trợ lực.',
    features: ['In liền khối không cần vòng bi ngoài', 'Kiểm tra độ chuẩn xác dung sai máy', 'Quay êm ái khi hoàn thiện'],
    thumbnailUrl: '/thumbnails/gear.svg',
    badge: 'Miễn phí 100%',
  },
  {
    id: 'mod-headphone-hanger',
    type: 'model',
    title: 'Minimalist Under-Desk Headphone Hanger – Giá Treo Tai Nghe Gầm Bàn',
    author: 'MakerStudio',
    isFree: true,
    priceVnd: 0,
    category: 'tools',
    formats: ['.STL', '.3MF'],
    downloads: 12500,
    likes: 3800,
    rating: 4.8,
    reviewsCount: 195,
    difficulty: 'Dễ in',
    printTimeEstimate: '1h 45m',
    filamentWeightEstimate: '45g',
    description: 'Móc treo tai nghe giấu gầm bàn làm việc thông minh. Thiết kế vát công thái học không làm lún đệm mút tai nghe, chịu lực lên tới 5kg.',
    features: ['Gắn bằng băng keo 3M hoặc vít', 'Rãnh cuộn dây tai nghe gọn gàng', 'In chịu lực góc ngang 100% infill'],
    thumbnailUrl: '/thumbnails/headphone-hanger.svg',
    badge: 'Miễn phí 100%',
  },
  {
    id: 'mod-gridfinity-box',
    type: 'model',
    title: 'Gridfinity Modular Bin Organizer – Hộp Đựng Linh Kiện Mô-đun Thông Minh',
    author: 'ZackFreedman',
    isFree: true,
    priceVnd: 0,
    category: 'tools',
    formats: ['.STL', '.STEP'],
    downloads: 21300,
    likes: 6700,
    rating: 4.9,
    reviewsCount: 410,
    difficulty: 'Dễ in',
    printTimeEstimate: '2h 10m',
    filamentWeightEstimate: '60g',
    description: 'Hệ thống khay sắp xếp đồ nghề Gridfinity chuẩn mở thế giới: có hốc gắn nam châm đáy, xếp chồng vững chắc, phân loại ốc vít và phụ kiện in 3D.',
    features: ['Chuẩn Gridfinity 42mm tiêu chuẩn', 'Hốc gắn nam châm 6x2mm', 'Dễ dàng mở rộng không giới hạn'],
    thumbnailUrl: '/thumbnails/gridfinity.svg',
    badge: 'Miễn phí 100%',
  },

  // --- MÔ HÌNH TRẢ PHÍ (PREMIUM) ---
  {
    id: 'mod-mecha-gundam-titan',
    type: 'model',
    title: 'Mecha Titan RX-78 Full Articulation – Robot Chiến Đấu Đa Khớp Khung Xương Nội Tại',
    author: 'ToyMakr3D Studio',
    isFree: false,
    priceVnd: 125000,
    originalPriceVnd: 180000,
    category: 'figure',
    formats: ['.STL', '.3MF', '.STEP', 'PDF Guide'],
    downloads: 3200,
    likes: 2100,
    rating: 5.0,
    reviewsCount: 145,
    difficulty: 'Cần chú ý Support',
    sampleModelId: 'robot',
    printTimeEstimate: '22h 30m',
    filamentWeightEstimate: '450g',
    description: 'Mô hình Mecha cao 32cm với hơn 86 chi tiết lắp ghép bằng chốt snap-fit. Khung xương bên trong cử động linh hoạt mọi tư thế, tặng kèm sách hướng dẫn lắp ráp PDF 24 trang.',
    features: ['Khung xương nội tại cử động 360 độ', 'Có hốc LED chiếu sáng mắt và ngực', 'Kèm file 3MF tô màu sẵn cho AMS'],
    thumbnailUrl: '/thumbnails/robot.svg',
    badge: 'Best Seller',
  },
  {
    id: 'mod-cyberpunk-helmet',
    type: 'model',
    title: 'Cyberpunk Oni Helmet Wearable 1:1 – Nón Cosplay Đội Vừa Đầu Kèm Kính Trượt',
    author: 'ArmoryProps',
    isFree: false,
    priceVnd: 180000,
    originalPriceVnd: 250000,
    category: 'art_decor',
    formats: ['.STL', '.3MF', '.OBJ'],
    downloads: 1950,
    likes: 1800,
    rating: 4.9,
    reviewsCount: 92,
    difficulty: 'Cần chú ý Support',
    sampleModelId: 'helmet',
    printTimeEstimate: '36h',
    filamentWeightEstimate: '820g',
    description: 'Nón bảo hộ phong cách khoa học viễn tưởng tỉ lệ 1:1 có thể đội vừa đầu người lớn (chu vi vòng đầu 56-62cm). Thiết kế cắt module sẵn để in vừa khổ máy 256x256mm.',
    features: ['Cắt sẵn khớp ghép chốt căn chỉnh', 'Cơ chế kính chắn trượt mở cơ khí', 'Rãnh giấu dây LED Neon trang trí'],
    thumbnailUrl: '/thumbnails/helmet.svg',
    badge: 'Độc quyền',
  },
  {
    id: 'mod-mechanical-tourbillon-clock',
    type: 'model',
    title: 'Tourbillon Mechanical Clock – Đồng Hồ Cơ Khí Dây Cót Chạy Thật 100%',
    author: 'MechanicGenius',
    isFree: false,
    priceVnd: 95000,
    originalPriceVnd: 140000,
    category: 'mechanical',
    formats: ['.STL', '.STEP', 'Wiring Diagram'],
    downloads: 2450,
    likes: 1650,
    rating: 4.9,
    reviewsCount: 110,
    difficulty: 'Cần chú ý Support',
    sampleModelId: 'turbine',
    printTimeEstimate: '18h',
    filamentWeightEstimate: '380g',
    description: 'Đỉnh cao cơ khí in 3D: Cụm cân bằng Tourbillon tự triệt tiêu trọng lực giúp giữ nhịp giây chính xác. Hoạt động nhờ thế năng tạ treo hoặc cót lò xo không cần pin.',
    features: ['Chạy giờ thật sai số < 2 phút/ngày', 'Hộp số thoát Escapement nhịp 1Hz', 'Chỉ cần thêm vài ốc vít M3 thông dụng'],
    thumbnailUrl: '/thumbnails/turbine.svg',
    badge: 'Độ chính xác cao',
  },
  {
    id: 'mod-moon-lithophane-lamp',
    type: 'model',
    title: 'NASA 8K Moon Lithophane Lamp – Đèn Mặt Trăng 3D Chi Tiết Địa Hình Thực Tế',
    author: 'AstroDesign',
    isFree: false,
    priceVnd: 45000,
    originalPriceVnd: 60000,
    category: 'art_decor',
    formats: ['.STL', '.3MF'],
    downloads: 4100,
    likes: 2900,
    rating: 4.8,
    reviewsCount: 204,
    difficulty: 'Dễ in',
    printTimeEstimate: '14h',
    filamentWeightEstimate: '220g',
    description: 'Dựng từ bản đồ độ cao vệ tinh Lunar Reconnaissance Orbiter của NASA. Khi lắp đèn LED bên trong, bóng tối và ánh sáng hiện lên các miệng núi lửa y như mặt trăng thật.',
    features: ['Bản đồ độ cao NASA thực tế', 'Tích hợp đế ren gắn đui đèn E27', 'Bề mặt liền khối không mí nối'],
    thumbnailUrl: '/thumbnails/moon-lamp.svg',
    badge: 'Best Seller',
  },
];
