import { IModel3D, ITrendMetric } from '../domain/models';

export const INITIAL_MODELS: IModel3D[] = [
  // 1. Toys & Games / Print-in-Place
  {
    id: 'mw-101',
    title: 'Articulated Crystal Dragon V3 - Print-in-Place',
    author: 'Cinderwing3D',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/101',
    thumbnailUrl: '/thumbnails/dragon.svg',
    downloads: 148920,
    prints: 48210,
    likes: 68400,
    tags: ['articulated', 'dragon', 'print-in-place', 'fidget', 'toy', 'silk-pla'],
    category: 'Toys & Games',
    filamentType: 'PLA Silk Dual Color',
    filamentWeightGrams: 145,
    printTimeMinutes: 280,
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-10-04T12:00:00Z',
  },
  {
    id: 'mw-102',
    title: 'Gridfinity Modular Desk Organizer Master System',
    author: 'ZackFreedman',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/102',
    thumbnailUrl: '/thumbnails/gridfinity.svg',
    downloads: 162400,
    prints: 69500,
    likes: 89100,
    tags: ['gridfinity', 'organization', 'workshop', 'modular', 'functional', 'storage'],
    category: 'Household',
    filamentType: 'PLA Basic',
    filamentWeightGrams: 85,
    printTimeMinutes: 140,
    createdAt: '2026-07-20T08:30:00Z',
    updatedAt: '2026-10-04T18:00:00Z',
  },
  {
    id: 'mw-103',
    title: 'Bambu Lab AMS Lite Top Mount Extender Bracket',
    author: 'MakerModder',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/103',
    thumbnailUrl: '/thumbnails/bambu-acc.svg',
    downloads: 71800,
    prints: 32400,
    likes: 45300,
    tags: ['bambu', 'ams', 'upgrade', 'functional', 'a1-mini', 'accessories'],
    category: '3D Printer Accessories',
    filamentType: 'PETG / PLA-CF',
    filamentWeightGrams: 180,
    printTimeMinutes: 220,
    createdAt: '2026-09-01T14:15:00Z',
    updatedAt: '2026-10-04T20:30:00Z',
  },
  {
    id: 'mw-104',
    title: 'HueForge Cyberpunk City Skyline Wall Art (4-Color Filament)',
    author: 'PixelForge3D',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/104',
    thumbnailUrl: '/thumbnails/hueforge.svg',
    downloads: 58450,
    prints: 24900,
    likes: 38700,
    tags: ['hueforge', 'art', 'decor', 'multi-color', 'cyberpunk', 'wall-art'],
    category: 'Art & Decoration',
    filamentType: 'PLA Matte',
    filamentWeightGrams: 65,
    printTimeMinutes: 110,
    createdAt: '2026-09-18T09:00:00Z',
    updatedAt: '2026-10-04T16:45:00Z',
  },
  {
    id: 'pr-201',
    title: 'Rugged Waterproof EDC Utility Box with TPU O-Ring',
    author: 'Whity_Engineer',
    platform: 'printables',
    sourceUrl: 'https://www.printables.com/model/201',
    thumbnailUrl: '/thumbnails/rugged-box.svg',
    downloads: 84100,
    prints: 38800,
    likes: 52100,
    tags: ['rugged', 'case', 'waterproof', 'functional', 'edc', 'storage'],
    category: 'Tools & Utilities',
    filamentType: 'PETG / TPU 95A',
    filamentWeightGrams: 210,
    printTimeMinutes: 340,
    createdAt: '2026-08-10T11:00:00Z',
    updatedAt: '2026-10-04T19:00:00Z',
  },
  {
    id: 'mw-105',
    title: 'Pumpkin Treat Bucket with Pop-up Skull Mechanism',
    author: 'SpookyPrints',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/105',
    thumbnailUrl: '/thumbnails/pumpkin.svg',
    downloads: 69500,
    prints: 29200,
    likes: 44600,
    tags: ['halloween', 'pumpkin', 'pop-up', 'mechanism', 'seasonal', 'fidget'],
    category: 'Seasonal & Holiday',
    filamentType: 'PLA Orange / Glow',
    filamentWeightGrams: 160,
    printTimeMinutes: 260,
    createdAt: '2026-09-22T15:00:00Z',
    updatedAt: '2026-10-04T22:15:00Z',
  },
  {
    id: 'th-301',
    title: 'Precision Collapsible Laptop Stand - Travel Edition',
    author: 'NomadMaker',
    platform: 'thingiverse',
    sourceUrl: 'https://www.thingiverse.com/thing:301',
    thumbnailUrl: '/thumbnails/laptop-stand.svg',
    downloads: 91200,
    prints: 41700,
    likes: 58000,
    tags: ['laptop-stand', 'portable', 'foldable', 'desk', 'ergonomic', 'gadgets'],
    category: 'Gadgets',
    filamentType: 'ABS / PETG',
    filamentWeightGrams: 110,
    printTimeMinutes: 180,
    createdAt: '2026-06-12T07:20:00Z',
    updatedAt: '2026-10-04T15:30:00Z',
  },

  // 2. More Iconic Trending Models
  {
    id: 'mw-106',
    title: 'Bambu Lab X1C Poop Chute with Dual Silicone Wiper',
    author: 'ChuteMaster',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/106',
    thumbnailUrl: '/thumbnails/bambu-acc.svg',
    downloads: 82300,
    prints: 43100,
    likes: 51200,
    tags: ['bambu', 'x1c', 'p1s', 'poop-chute', 'purge', 'accessories'],
    category: '3D Printer Accessories',
    filamentType: 'PETG / ABS',
    filamentWeightGrams: 115,
    printTimeMinutes: 165,
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-10-04T21:00:00Z',
  },
  {
    id: 'pr-202',
    title: 'Parametric Honeycomb Storage Wall (HSW) System Core',
    author: 'RostaP',
    platform: 'printables',
    sourceUrl: 'https://www.printables.com/model/202',
    thumbnailUrl: '/thumbnails/hsw.svg',
    downloads: 198000,
    prints: 92400,
    likes: 124500,
    tags: ['hsw', 'honeycomb', 'wall-storage', 'organization', 'workshop'],
    category: 'Household',
    filamentType: 'PETG / PLA Tough',
    filamentWeightGrams: 175,
    printTimeMinutes: 290,
    createdAt: '2026-05-15T09:00:00Z',
    updatedAt: '2026-10-04T19:30:00Z',
  },
  {
    id: 'mw-107',
    title: 'Cyberpunk Oni Warrior Mask with Filter Ports',
    author: 'Kage3D',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/107',
    thumbnailUrl: '/thumbnails/oni-mask.svg',
    downloads: 45600,
    prints: 18900,
    likes: 31200,
    tags: ['cyberpunk', 'mask', 'cosplay', 'helmet', 'props', 'mecha'],
    category: 'Cosplay & Props',
    filamentType: 'PLA-CF / ABS',
    filamentWeightGrams: 230,
    printTimeMinutes: 380,
    createdAt: '2026-09-05T13:20:00Z',
    updatedAt: '2026-10-04T17:15:00Z',
  },
  {
    id: 'th-302',
    title: 'Flexi Rex with Articulated Tail & Moving Jaw',
    author: 'DrLex',
    platform: 'thingiverse',
    sourceUrl: 'https://www.thingiverse.com/thing:302',
    thumbnailUrl: '/thumbnails/flexi-rex.svg',
    downloads: 245000,
    prints: 112000,
    likes: 145000,
    tags: ['flexi-rex', 'dinosaur', 'print-in-place', 'articulated', 'toy'],
    category: 'Toys & Games',
    filamentType: 'PLA Basic',
    filamentWeightGrams: 42,
    printTimeMinutes: 65,
    createdAt: '2026-04-10T08:00:00Z',
    updatedAt: '2026-10-04T14:00:00Z',
  },
  {
    id: 'mw-108',
    title: 'Minimalist Spiral Twist Modern Vase (Vase Mode Ready)',
    author: 'VaseLab3D',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/108',
    thumbnailUrl: '/thumbnails/spiral-vase.svg',
    downloads: 67800,
    prints: 38400,
    likes: 47200,
    tags: ['vase-mode', 'spiral', 'modern', 'home-decor', 'aesthetic'],
    category: 'Art & Decoration',
    filamentType: 'PLA Silk / PETG Translucent',
    filamentWeightGrams: 60,
    printTimeMinutes: 85,
    createdAt: '2026-08-30T16:00:00Z',
    updatedAt: '2026-10-04T18:45:00Z',
  },
  {
    id: 'pr-203',
    title: 'Voron Stealthburner Toolhead with Neopixel & CW2 Extruder',
    author: 'VoronDesign',
    platform: 'printables',
    sourceUrl: 'https://www.printables.com/model/203',
    thumbnailUrl: '/thumbnails/voron-toolhead.svg',
    downloads: 78900,
    prints: 39500,
    likes: 54100,
    tags: ['voron', 'stealthburner', 'toolhead', 'corexy', 'upgrade', 'functional'],
    category: '3D Printer Accessories',
    filamentType: 'ABS / ASA (Nhiệt độ cao)',
    filamentWeightGrams: 160,
    printTimeMinutes: 270,
    createdAt: '2026-07-14T10:30:00Z',
    updatedAt: '2026-10-04T22:00:00Z',
  },
  {
    id: 'mw-109',
    title: 'Gravity Fidget Karambit Folding Knife (Safe Toy)',
    author: 'FidgetForge',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/109',
    thumbnailUrl: '/thumbnails/karambit.svg',
    downloads: 114000,
    prints: 56200,
    likes: 72800,
    tags: ['fidget', 'karambit', 'gravity-knife', 'toy', 'print-in-place'],
    category: 'Toys & Games',
    filamentType: 'PLA Matte Dual',
    filamentWeightGrams: 55,
    printTimeMinutes: 95,
    createdAt: '2026-09-12T14:00:00Z',
    updatedAt: '2026-10-04T23:00:00Z',
  },
  {
    id: 'th-303',
    title: 'Heavy Duty C-Clamp with Reinforced Trapezoidal Thread',
    author: 'ToolMakerPro',
    platform: 'thingiverse',
    sourceUrl: 'https://www.thingiverse.com/thing:303',
    thumbnailUrl: '/thumbnails/c-clamp.svg',
    downloads: 62100,
    prints: 28400,
    likes: 39500,
    tags: ['clamp', 'workshop', 'tools', 'woodworking', 'mechanical'],
    category: 'Tools & Utilities',
    filamentType: 'PETG / PLA+',
    filamentWeightGrams: 190,
    printTimeMinutes: 310,
    createdAt: '2026-06-25T11:45:00Z',
    updatedAt: '2026-10-04T16:20:00Z',
  },
  {
    id: 'mw-110',
    title: 'Moon Lamp 3D Spherical Night Light with E27 Socket',
    author: 'LunarDesign',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/110',
    thumbnailUrl: '/thumbnails/moon-lamp.svg',
    downloads: 87500,
    prints: 41200,
    likes: 56900,
    tags: ['moon-lamp', 'lithophane', 'lighting', 'home-decor', 'night-light'],
    category: 'Art & Decoration',
    filamentType: 'PLA White Lithophane',
    filamentWeightGrams: 280,
    printTimeMinutes: 520,
    createdAt: '2026-08-08T09:15:00Z',
    updatedAt: '2026-10-04T20:10:00Z',
  },
  {
    id: 'pr-204',
    title: 'Original Prusa Anti-Vibration TPU Sorbothane Feet',
    author: 'SilentPrinters',
    platform: 'printables',
    sourceUrl: 'https://www.printables.com/model/204',
    thumbnailUrl: '/thumbnails/bambu-acc.svg',
    downloads: 53400,
    prints: 29800,
    likes: 38200,
    tags: ['prusa', 'anti-vibration', 'tpu', 'silent', 'noise-reduction'],
    category: '3D Printer Accessories',
    filamentType: 'TPU 95A / 85A',
    filamentWeightGrams: 48,
    printTimeMinutes: 75,
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-10-04T17:30:00Z',
  },
  {
    id: 'mw-111',
    title: 'Modular Cable Management Clip System (Under-Desk)',
    author: 'CleanDesk3D',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/111',
    thumbnailUrl: '/thumbnails/headphone-hanger.svg',
    downloads: 94200,
    prints: 49800,
    likes: 61500,
    tags: ['cable-clip', 'cable-management', 'desk', 'organization', 'household'],
    category: 'Household',
    filamentType: 'PLA / PETG',
    filamentWeightGrams: 35,
    printTimeMinutes: 50,
    createdAt: '2026-08-20T12:00:00Z',
    updatedAt: '2026-10-04T19:40:00Z',
  },
  {
    id: 'th-304',
    title: 'Articulated Cute Octopus with Waving Tentacles',
    author: 'McGybeer',
    platform: 'thingiverse',
    sourceUrl: 'https://www.thingiverse.com/thing:304',
    thumbnailUrl: '/thumbnails/octopus.svg',
    downloads: 182000,
    prints: 89000,
    likes: 118000,
    tags: ['octopus', 'articulated', 'print-in-place', 'fidget', 'toy'],
    category: 'Toys & Games',
    filamentType: 'PLA Silk Purple',
    filamentWeightGrams: 75,
    printTimeMinutes: 135,
    createdAt: '2026-05-28T08:30:00Z',
    updatedAt: '2026-10-04T16:00:00Z',
  },
  {
    id: 'mw-112',
    title: 'Functional Airless Basketball - Full Size 7 Bounce Test',
    author: 'AeroBall',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/112',
    thumbnailUrl: '/thumbnails/airless-ball.svg',
    downloads: 125000,
    prints: 42000,
    likes: 83000,
    tags: ['airless-basketball', 'tpu', 'sports', 'functional', 'elastic'],
    category: 'Gadgets',
    filamentType: 'TPU 95A / 90A',
    filamentWeightGrams: 380,
    printTimeMinutes: 720,
    createdAt: '2026-09-10T11:00:00Z',
    updatedAt: '2026-10-04T22:30:00Z',
  },
  {
    id: 'pr-205',
    title: 'Dial Indicator Bed Leveling Tramming Mount for Prusa MK3/MK4',
    author: 'PrecisionMaker',
    platform: 'printables',
    sourceUrl: 'https://www.printables.com/model/205',
    thumbnailUrl: '/thumbnails/caliper.svg',
    downloads: 38400,
    prints: 17200,
    likes: 26800,
    tags: ['dial-indicator', 'tramming', 'bed-leveling', 'tools', 'prusa'],
    category: 'Tools & Utilities',
    filamentType: 'PETG / ABS',
    filamentWeightGrams: 58,
    printTimeMinutes: 90,
    createdAt: '2026-07-04T14:15:00Z',
    updatedAt: '2026-10-04T18:10:00Z',
  },
  {
    id: 'mw-113',
    title: 'Christmas Rotating Snowman Music Box Mechanism',
    author: 'HolidayCheer3D',
    platform: 'makerworld',
    sourceUrl: 'https://makerworld.com/en/models/113',
    thumbnailUrl: '/thumbnails/snowman.svg',
    downloads: 51200,
    prints: 23400,
    likes: 37900,
    tags: ['christmas', 'snowman', 'holiday', 'music-box', 'seasonal', 'gears'],
    category: 'Seasonal & Holiday',
    filamentType: 'PLA Multi-Color',
    filamentWeightGrams: 210,
    printTimeMinutes: 360,
    createdAt: '2026-09-28T16:00:00Z',
    updatedAt: '2026-10-04T23:15:00Z',
  },
  {
    id: 'th-305',
    title: 'Stackable 18650 & 21700 Battery Caddy with Latch',
    author: 'BatteryBoxer',
    platform: 'thingiverse',
    sourceUrl: 'https://www.thingiverse.com/thing:305',
    thumbnailUrl: '/thumbnails/battery-caddy.svg',
    downloads: 76500,
    prints: 39100,
    likes: 51400,
    tags: ['battery', '18650', '21700', 'storage', 'household', 'safety'],
    category: 'Household',
    filamentType: 'PETG Fire-Retardant',
    filamentWeightGrams: 125,
    printTimeMinutes: 195,
    createdAt: '2026-06-18T10:00:00Z',
    updatedAt: '2026-10-04T17:50:00Z',
  },
];
